### ISSUE TITLE
Issue when no GitHub token specified

### ISSUE THREAD

**Issue by sneko** [Philmod/google-container-slack#32]
Hi @Philmod ,

When not specifying the `$GITHUB_TOKEN` environment variable I receive on Slack:
`Error: TypeError: Cannot read property 'author' of undefined`

And in the Functions logs:
`TypeError: Cannot read property 'git' of undefined at Object.module.exports.getGithubCommit (/srv/index.js:18:40) at module.exports.subscribe (/srv/index.js:48:47) at /worker/worker.js:825:24 at <anonymous> at process._tickDomainCallback (internal/process/next_tick.js:229:7)`
_(not the right log line since I added some logs to debug...)_

I will make a PR that fixes that.

**Comment by plutov** [comment]
Same happens to me. The slack integration stopped working
